* BrainrotOS

Work in progress proof of concept for a user friendly "immutable" distribution like Bazzite, but based on NixOS. 

** Rough plan

This repository defines nix options, e.g. =brainrotos.firefox.v1.enable=, which correspond to NixOS configuration, like enabling firefox in this case.

Options are versioned to enable easier updates to the repository, without required user action, though the naming scheme is not locked in yet, due to the very early state of this project.

Your BrainrotOS machine contains a local nix configuration, in =/nix/osconfig/default.nix=, that sets these options to something. 

Your machine builds the flake in =--impure= mode, and the flake imports the local configuration.

*** More detail

The set of options should be simplistic, to not overcomplicate the project. The point should be to account for most basic usecases, advanced users can always edit the plain nix configuration.

Option versioning will allow me to update options while adapting older options to newer ones, so that in an optimal scenario the end user doesn't have to do anything to their configuration, if for example =example.v1.setting= is a =str=, and =example.v2.setting= is a =listOf str=, there can be a module like this:

#+begin_src nix
{config, ...}: {
  example.v2.setting = [config.example.v1.setting];
}
#+end_src

Importing a json or toml file in the local config will be done easily, there can be an editing gui for the limited set of exposed options later. A default config should be generated by the installer.

*** In practice

BrainrotOS will ship with hopefully good flatpak and appimage support, most normal users should be encouraged to use those distribution methods for their applications, as if they are on an image based distro like ublue.

The bazaar flatpak store is currently installed as a flatpak on first boot, there is some sample configuration and some setup to run it as a background service for the user and automatically enable the gnome search provider.

If this project goes anywhere, I can easily do flake updates and builds in github actions, and use something as a binary cache. Then the machines can run =nixos-rebuild boot= occasionally to stay up to date automatically.

The target userbase will probably get by with a browser, steam and some basic utilities, but because of the NixOS base, you will have the full power of nix. I am not 100% sure if you can run a standalone home-manager installation on top of this, but that would be the dream.

** Installation

These instructions will obviously change to become more user friendly and less rigid later. This is easiest to complete from a NixOS live iso.

Create two partitions, a =FAT32= boot partition with the =esp= flag set, and a btrfs main partition.

The boot partition should be labeled =BROS_BOOT= and the main partition should be labeled =bros-main=.

Create the subvolumes =@nix=, =@home=, =@tmp= and =@var_tmp= on the btrfs partition.

Create =/mnt/boot= and =/mnt/nix=, and mount the correct partitions.
#+begin_src shell
sudo mkdir /mnt/boot /mnt/nix
sudo mount /dev/disk/by-label/BROS_BOOT /mnt/boot
sudo mount /dev/disk/by-label/bros-main -o subvol=@nix /mnt/nix
#+end_src

Create a local system confguration in =/mnt/nix/osconfig/default.nix=, here's a good base:

#+begin_src nix
{
  config = {
    brainrotos = {
      desktop.gnome.v1.enable = true;
      firefox.v1.enable = true;
      user.v1.name = "user";
    };

    nixpkgs.hostPlatform = {system = "x86_64-linux";};
    system.stateVersion = "25.11";
  };
}
#+end_src

After this you can proceed with the installation

#+begin_src shell
nixos-install --impure --no-root-password --no-channel-copy -I brainrotos=/mnt/nix/osconfig --flake github:thundertheidiot/brainrotos#base 
#+end_src

The default password of the user account is =password123=, this can be changed and the change is persisted.

* TODOs

- [ ] TODO automatic rollback
  - [ ] boot validation
  - [ ] boot counting
- [ ] krunner bazaar
- [ ] GPU configs
  - [ ] better vm support?
  - [ ] amd
  - [ ] nvidia
  - [ ] intel
