# shellcheck shell=bash
# brainrotos boot validation - grub loader hooks
#
# Sourced by the shared core (boot-validation.sh). Functions and variables
# that look unassigned here (grubenv_*, prev_gen, log/fail, GRUBENV, ...)
# are defined there.

# replicates the entry titles generated by install-grub.pl
grub_fallback_entry() {
  local link gen_date version title
  link="/nix/var/nix/profiles/system-$1-link"
  gen_date=$(date -d "@$(stat -c %Y "$link")" +%F 2>/dev/null) || return 1
  version=$(cat "$link/nixos-version" 2>/dev/null) || true
  if [ -z "$version" ]; then
    version=$(basename "$(readlink -f "$link/kernel")" 2>/dev/null) || true
  fi
  [ -n "$version" ] || return 1
  title="NixOS - Configuration $1"
  if [ -d "$link/specialisation" ] && [ -n "$(ls -A "$link/specialisation" 2>/dev/null)" ]; then
    title="$title - Default"
  fi
  echo "NixOS - All configurations>$title ($gen_date - $version)"
}

loader_arm() {
  # pre-compute the fallback entry title at arm time: the boot snippet
  # steers with it even if userspace never runs again
  # $1 = booted generation (unused on grub), $2 = fallback generation
  local prev="$2" title
  if title=$(grub_fallback_entry "$prev"); then
    grubenv_set bros_fallback_entry "$title"
  else
    fail "cannot compute grub fallback entry for generation $prev"
  fi
}

loader_retry() {
  # grub decrements the boot counter itself, inside the bootloader
  :
}

loader_exhausted_ensure() {
  # grub steers via its config snippet reading bros_fallback_entry
  :
}

loader_steer() {
  local title
  title=$(grub_fallback_entry "$1") || {
    fail "cannot compute grub entry for generation $1"
    return 1
  }
  grubenv_set bros_boot_entry "$title"
}

loader_unsteer() {
  grubenv_unset bros_boot_entry
}

loader_exhausted_select() {
  # $1 = booted generation (steering is via bros_fallback_entry here)
  local prev="$2" title
  title=$(grubenv_get bros_fallback_entry)
  if [ -z "$title" ]; then
    title=$(grub_fallback_entry "$prev") || {
      fail "cannot compute fallback entry; manual intervention required"
      return 1
    }
    grubenv_set bros_fallback_entry "$title"
  fi
}
