#!/usr/bin/env bash
# brainrotos boot validation helper
#
# The placeholders in this file are substituted by pkgs.replaceVarsWith
# in boot/validation.nix.

GRUBENV="${BRAINROTOS_GRUBENV:-@grubenv@}"
LOADER_CONF="${BRAINROTOS_LOADER_CONF:-@loaderConf@}"
ATTEMPTS=@attempts@
TIMEOUT=@timeout@
BOOTLOADER="@bootLoader@"

log() {
  echo "brainrotos-boot-validation: $*"
}

fail() {
  echo "brainrotos-boot-validation: $*" >&2
}

grubenv_get() {
  grub-editenv "$GRUBENV" list 2>/dev/null | sed -n "s/^$1=//p" | head -n 1 || true
}

grubenv_set() {
  grub-editenv "$GRUBENV" set "$1=$2"
}

grubenv_unset() {
  grub-editenv "$GRUBENV" unset "$1"
}

gen_number() {
  local link
  link=$(readlink /nix/var/nix/profiles/system) || return 1
  sed -n 's/^.*system-\([0-9]\+\)-link$/\1/p' <<< "$link"
}

prev_gen() {
  local link n best=0
  for link in /nix/var/nix/profiles/system-*-link; do
    [ -e "$link" ] || continue
    n=${link##*system-}
    n=${n%-link}
    if [ "$n" -lt "$1" ] 2>/dev/null && [ "$n" -gt "$best" ]; then
      best=$n
    fi
  done
  if [ "$best" -gt 0 ]; then
    echo "$best"
  fi
}

# replicates the entry titles generated by install-grub.pl
grub_fallback_entry() {
  local link gen_date version title
  link="/nix/var/nix/profiles/system-$1-link"
  gen_date=$(date -d "@$(stat -c %Y "$link")" +%F 2>/dev/null) || return 1
  version=$(cat "$link/nixos-version" 2>/dev/null)
  if [ -z "$version" ]; then
    version=$(basename "$(readlink -f "$link/kernel")" 2>/dev/null)
  fi
  [ -n "$version" ] || return 1
  title="NixOS - Configuration $1"
  if [ -d "$link/specialisation" ] && [ -n "$(ls -A "$link/specialisation" 2>/dev/null)" ]; then
    title="$title - Default"
  fi
  echo "NixOS - All configurations>$title ($gen_date - $version)"
}

loader_set_default() {
  local entries_dir entry="" f
  if [ ! -f "$LOADER_CONF" ]; then
    return 1
  fi
  entries_dir="$(dirname "$LOADER_CONF")/entries"
  for f in "$entries_dir"/nixos-generation-"$1"*.conf; do
    [ -e "$f" ] || continue
    case "$f" in *specialisation*) continue ;; esac
    entry=$f
    break
  done
  [ -n "$entry" ] || return 1
  # replace any default line (nixos writes one on every rebuild)
  sed -i '/# brainrotos boot validation/d; /^default /d' "$LOADER_CONF"
  printf '# brainrotos boot validation\ndefault %s\n' "$(basename "$entry")" >> "$LOADER_CONF"
}

loader_clear_default() {
  if [ -f "$LOADER_CONF" ]; then
    sed -i '/# brainrotos boot validation/,+1d' "$LOADER_CONF"
  fi
}

prepare() {
  if [ ! -f "$GRUBENV" ]; then
    grub-editenv "$GRUBENV" create
  fi
  local gen armed lastgood counter prev title
  gen=$(gen_number) || {
    fail "cannot determine system generation"
    return 1
  }
  armed=$(grubenv_get bros_armed_gen)
  lastgood=$(grubenv_get bros_last_good_gen)
  counter=$(grubenv_get boot_counter)

  if [ "$gen" = "$lastgood" ]; then
    return 0
  fi

  if [ "$gen" != "$armed" ]; then
    # first boot (or first switch) of an unvalidated generation:
    # clear any stale cycle, then arm a fresh one
    prev=$(prev_gen "$gen")
    if [ -z "$prev" ]; then
      fail "no previous generation to fall back to; boot validation not armed"
      return 0
    fi
    grubenv_unset boot_counter
    grubenv_unset bros_fallback_entry
    grubenv_unset bros_fallback_target
    grubenv_set bros_armed_gen "$gen"
    grubenv_set boot_counter "$ATTEMPTS"
    if [ "$BOOTLOADER" = "grub" ]; then
      if title=$(grub_fallback_entry "$prev"); then
        grubenv_set bros_fallback_entry "$title"
      else
        fail "cannot compute grub fallback entry for generation $prev"
      fi
    fi
    log "armed validation for generation $gen ($ATTEMPTS attempts, fallback: generation $prev)"
  elif [ -n "$counter" ] && [ "$counter" -gt 0 ] 2>/dev/null; then
    # retry boot of the armed generation; grub already decremented
    # pre-boot, systemd-boot needs a hand
    if [ "$BOOTLOADER" = "systemd-boot" ]; then
      counter=$((counter - 1))
      grubenv_set boot_counter "$counter"
      if [ "$counter" -eq 0 ]; then
        if prev=$(prev_gen "$gen") && loader_set_default "$prev"; then
          grubenv_set bros_fallback_target "$prev"
          log "attempts exhausted; systemd-boot will fall back to generation $prev"
        else
          fail "attempts exhausted but cannot select a fallback entry"
        fi
      fi
    fi
  elif [ -n "$counter" ]; then
    # counter already exhausted (e.g. reset before the failure hook
    # ran); make sure the fallback selection is in place
    if [ "$BOOTLOADER" = "systemd-boot" ]; then
      if prev=$(prev_gen "$gen"); then
        loader_set_default "$prev" || true
      fi
    fi
  fi
}

login_watchdog() {
  local deadline=$((SECONDS + TIMEOUT))
  while [ "$SECONDS" -lt "$deadline" ]; do
    if loginctl --no-legend list-sessions 2>/dev/null \
      | awk '$2 ~ /^[0-9]+$/ && $2 + 0 >= 1000 { found = 1 } END { exit !found }'; then
      log "user session detected; boot validated"
      return 0
    fi
    sleep 5
  done
  fail "no user login within $TIMEOUT s; declaring boot failed"
  return 1
}

on_success() {
  local gen
  gen=$(gen_number) || return 0
  grubenv_set bros_last_good_gen "$gen"
  if [ "$BOOTLOADER" = "systemd-boot" ]; then
    loader_clear_default
  fi
  log "generation $gen recorded as last good"
}

on_fail() {
  local counter gen prev title target
  counter=$(grubenv_get boot_counter)
  # greenboot reboots on its own while retries remain
  if [ -z "$counter" ] || [ "$counter" -gt 0 ] 2>/dev/null; then
    return 0
  fi
  gen=$(gen_number) || return 0
  target=$(grubenv_get bros_fallback_target)
  if [ -n "$target" ] && [ "$target" = "$gen" ]; then
    fail "already booting the fallback generation; manual intervention required"
    return 0
  fi
  prev=$(prev_gen "$gen")
  if [ -z "$prev" ]; then
    fail "no previous generation to fall back to; manual intervention required"
    return 0
  fi
  if [ "$BOOTLOADER" = "grub" ]; then
    title=$(grubenv_get bros_fallback_entry)
    if [ -z "$title" ]; then
      title=$(grub_fallback_entry "$prev") || {
        fail "cannot compute fallback entry; manual intervention required"
        return 0
      }
      grubenv_set bros_fallback_entry "$title"
    fi
  else
    if ! loader_set_default "$prev"; then
      fail "cannot write systemd-boot fallback; manual intervention required"
      return 0
    fi
  fi
  grubenv_set bros_fallback_target "$prev"
  log "boot validation exhausted for generation $gen; rebooting into generation $prev"
  if [ -n "${BRAINROTOS_BOOT_VALIDATION_DRY_RUN:-}" ]; then
    log "dry run: would reboot into generation $prev"
  else
    shutdown -r +1 "brainrotos: boot validation failed $ATTEMPTS times - rebooting into previous generation $prev"
  fi
}

case "${1:-}" in
  prepare) prepare ;;
  login-watchdog) login_watchdog ;;
  on-success) on_success ;;
  on-fail) on_fail ;;
  *)
    fail "usage: brainrotos-boot-validation {prepare|login-watchdog|on-success|on-fail}"
    exit 2
    ;;
esac
